server:
  port: 8088
spring:
  application:
    name: jwt-example
  output:
    ansi:
      enabled: ALWAYS
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: 'update'
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_db
    username: postgres
    password: postgres
    hikari:
      schema: jwt_example_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS jwt_example_schema
      connection-timeout: 5000
#logging:
#  level:
#    org.springframework: DEBUG
user-service:
  jwt:
    secret: PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PA==
    tokenExpiration: 30m
    refreshTokenExpiration: 30m
