server:
  port: 8080

spring:
  application:
    name: jwt-example
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_db
    username: postgres
    password: postgres
    hikari:
      schema: jwt.example.schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS jwt.example.schema
      connection-timeout: 5000
user-service:
  jwt:
    secret: "dGhpcy1pcy1zZWNyZXQK" # Ð’ Base64
    tokenExpiration: 1m
    refreshExpiration: 10m
