version: '3.9'

services:
  redis:
    image: redis:8.0.2-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=secure_db
